cosmwasm grpc and rest clients
Entropy-Foundation/oracle-pull-example pull request #7
Opened 2024-06-21 15:10 UTC by harsh-supra

gRPC and REST clients for cosmwasm contracts

2024-06-21 15:22 UTC, nizam-supraoracles commented on gRPC/javascript/cosmwasm_client/main.js
> +
unused function

2024-06-21 15:22 UTC, nizam-supraoracles commented on gRPC/javascript/cosmwasm_client/main.js
> +const { SigningCosmWasmClient, fromBinary } = require('@cosmjs/cosmwasm-stargate');
`fromBinary` not used anywhere I guess

2024-06-21 15:22 UTC, nizam-supraoracles commented on gRPC/javascript/cosmwasm_client/package.json
> +    "@radixdlt/radix-engine-toolkit": "^1.0.3"
is the `radixdlt` package required in cosmwasm?

2024-06-21 15:22 UTC, nizam-supraoracles commented on gRPC/rust-sdks/cosmwasm_client/src/cosmwasm_connector.rs
> +    const ACCOUNT_NUMBER: AccountNumber = 25903;
Account number is depend on wallet address, so we can define like this `<ACCOUNT NUMBER>`

2024-06-21 15:22 UTC, nizam-supraoracles commented on gRPC/rust-sdks/cosmwasm_client/src/cosmwasm_connector.rs
> +    let sequence_number = 107;
`sequence_number` should not be static

2024-06-24 08:27 UTC, abrar-supra requested changes
Also add readme for all examples

2024-06-24 08:27 UTC, abrar-supra commented on gRPC/javascript/cosmwasm_client/package.json
> +    "@grpc/proto-loader": "^0.7.8",
remove `,`, it will cause build issue

2024-06-24 08:27 UTC, abrar-supra commented on gRPC/javascript/cosmwasm_client/pullServiceClient.js
> +    var PROTO_PATH = __dirname + '/../protos/client.proto';
invalid proto file path

2024-06-24 08:27 UTC, abrar-supra commented on gRPC/javascript/cosmwasm_client/main.js
> +    const [firstAccount] = await wallet.getAccounts();
remove if it is unused

2024-06-24 08:27 UTC, abrar-supra commented on gRPC/rust-sdks/cosmwasm_client/src/cosmwasm_connector.rs
> +    let (account_number,sequence_number) = collect_acc_sequence_number(rpc_url.to_string(),sender_account_id.clone());
causing build error, please check

2024-06-24 08:27 UTC, abrar-supra commented on gRPC/rust-sdks/cosmwasm_client/src/cosmwasm_connector.rs
> +    let mut grpc_client = QueryClient::connect(end_point).await?;
same here

2024-06-24 08:27 UTC, abrar-supra commented on gRPC/rust-sdks/cosmwasm_client/src/errors.rs
> +pub enum ConnectorError {}
remove it, if it is unused

2024-06-24 08:28 UTC, nizam-supraoracles requested changes

2024-06-24 08:28 UTC, nizam-supraoracles commented on gRPC/javascript/cosmwasm_client/package.json
>      "@grpc/proto-loader": "^0.7.8",
you also need to remove `,` from here, it's an incorrect JSON format

2024-06-24 08:28 UTC, nizam-supraoracles commented on gRPC/javascript/cosmwasm_client/pullServiceClient.js
> +    var PROTO_PATH = __dirname + '/../protos/client.proto';
incorrect proto path, it should be `/../../protos/client.proto`

2024-06-24 08:28 UTC, nizam-supraoracles commented on gRPC/rust-sdks/cosmwasm_client/src/cosmwasm_connector.rs
> +    let (account_number,sequence_number) = collect_acc_sequence_number(rpc_url.to_string(),sender_account_id.clone());
`collect_acc_sequence_number` is an **async** function and returns a Result, so you have to handle it accordingly

2024-06-24 08:28 UTC, nizam-supraoracles commented on rest/rust-sdks/cosmwasm_client/examples/cosmwasm_client.rs
> +            // call_contract(response).await;
`call_contract` function is commented, you have to enable it and test the same

2024-06-24 08:28 UTC, nizam-supraoracles commented on rest/javascript/cosmwasm_client/package.json
> +    "@grpc/proto-loader": "^0.7.8",
`,` remove from last line

2024-06-25 12:43 UTC, nizam-supraoracles approved these changes

2024-06-26 08:26 UTC, abrar-supra requested changes

2024-06-26 08:26 UTC, abrar-supra commented on rest/javascript/cosmwasm_client/package.json
> +  "description": "I've created a JavaScript library that streamlines gRPC requests to acquire Oracle proofs. These Oracle proofs are then put to use within the main.js file, where an illustrative exa
it should be,
`I've created a JavaScript library that streamlines rest/rpc requests to acquire Oracle proofs`

2024-06-26 08:26 UTC, abrar-supra commented on rest/rust-sdks/cosmwasm_client/README.md
> +The Rust PullServiceClient is designed to interact with a gRPC server for fetching proof data and using that data to
same as above

2024-06-26 08:26 UTC, abrar-supra commented on rest/rust-sdks/cosmwasm_client/README.md
> +The Rust library for Cosmwasm, Sui, Aptos and evm provides a complete example that fetches proof data from a gRPC server and then calls a
`...fetches proof data from a rest server and then calls`

2024-06-26 08:26 UTC, abrar-supra commented on rest/rust-sdks/cosmwasm_client/README.md
> +1. Set the gRPC server address:
rest server

2024-06-26 08:26 UTC, abrar-supra commented on rest/rust-sdks/cosmwasm_client/Cargo.toml
> +tonic-build = "0.10.2"
is it required now?

2024-06-26 08:26 UTC, abrar-supra commented on rest/rust-sdks/cosmwasm_client/README.md
> +    let address = "grpcs://testnet-dora-2.supra.com".to_string();
change rpc

2024-06-26 15:42 UTC, dhaval-supraoracles approved these changes
Only one comment look fine to me.

2024-06-27 06:43 UTC, abrar-supra approved these changes

2024-06-27 06:45 UTC, merged